version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install -q
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm test
  publish:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - deploy:
          name: NPM Publish
          command: |
            chmod +x publish.sh
            ./publish.sh

workflows:
  version: 2
  build_and_publish:
    jobs:
    - build:
        context: org-global
    - publish:
        context: org-global
        requires:
          - build

